### ISSUE TITLE
Ingest images into LabCAS

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-backend#1]
Create a collection in EDRN LabCAS for Benign Breast Disease Pathology Slide Images - linked to the BBD protocol (id – 331) and DCIS protocol351

Create two datasets under this collection.
1. The first dataset would have the original images (access limited to DMCC, JPL, NCI – per Jackie email 1/25/20)

2. The second dataset would have the de-identified images (Nobody should have access until DMCC receive the biomarker results from Andy Godwin.  Once we have that, then I think we are providing access to Case Western (Bera Kaustave) along with clinical data linked to the images. per Jackie email 1/25/20)

Link images to appropriate protocol id (first 3 digits of ID)

**Comment by nutjob4life** [comment]
Hi @AshishMahabal @hoodriverheather I think this probably belongs in [EDRN-metadata](https://github.com/EDRN/EDRN-metadata/) not `labcas-backend` but I'm not sure.

Regardless, it's been over 4 years and it looks like [this is already done](https://edrn-labcas.jpl.nasa.gov/labcas-ui/c/index.html?collection_id=BBD_Pathology_Slide_Images), so I'm closing this for now. Feel free to re-open it if something's amiss.
