### ISSUE TITLE
QC on file counts between LabCAS UI and Solr for LTP2

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/labcas-backend#10]
@nutjob4life Can you please confirm the total files match what’s in Solr? I pulled this from the Dev UI. I want to confirm the totals shown in the UI match what’s in Solr.
 
Here’s are total files we have received from sites, so far:
NYU – 15,671
BU – 120,072
Moffitt – 24,322
Toledo – 24,332
UCLA/VA – 24,332
Pittsburgh – 5,030
 
Here’s a link to the blinded site id sheet - [https://docs.google.com/spreadsheets/d/1hsdu2x47DBr7oz_PQJXvzwrCcxY33-p_/edit?](https://docs.google.com/spreadsheets/d/1hsdu2x47DBr7oz_PQJXvzwrCcxY33-p_/edit?gid=1353426649#gid=1353426649)

Additional info: I used the Virtual view to group by blinded site id/event ID

**Comment by nutjob4life** [comment]
@hoodriverheather so just for LTP2? Or for _all_ files in Solr?

**Comment by hoodriverheather** [comment]
@nutjob4life Just LTP2. For the sites listed above. 
Open the link to the blinded site id excel sheet. From the LTP2 tab, query solr for each BlindedSiteID and match to number of files listed next to each of the sites names. I didn't match up the names because I'm sending these to Matt Schabath.

Let me know if you have any questions. Happy to jump on a quick call.
thanks!

**Comment by nutjob4life** [comment]
@hoodriverheather oh thank heavens! Okay working on that

**Comment by nutjob4life** [comment]
Okay, querying Solr directly:

- NYU = 15671
- BU = 120072
- Moffitt = 24322
- Toledo = 24332
- Pittsburgh = 5030

However, I think the UCAL/VA should be:

- UCLA & VA = 194376

Maybe you had a copy/paste error? Your number for UCLA/VA is 24332, which is identical to your Toledo number.

**Comment by hoodriverheather** [comment]
@nutjob4life Yep. Thanks for catching my copy and paste error. Glad they all match.
